name: smart_house
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  screenshot: ^1.3.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # URL link
  url_launcher: ^6.1.10

  # Google Sing In
  firebase_auth: ^3.0.2
  google_sign_in: ^5.2.1
  # Google Icon
  font_awesome_flutter: ^10.4.0
  # State Management
  provider: ^6.0.5

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.0.0
  shared_preferences: ^2.0.11
  intl: ^0.17.0
  flutter_phoenix: ^1.0.0
  animation_wrappers: ^3.0.0
  blur: ^3.0.0
  syncfusion_flutter_gauges: ^20.2.44
  flutter_switch: ^0.3.2
  flutter_colorpicker: ^1.0.3
  sizer: ^2.0.15
  timer_count_down: ^2.2.2
  sleek_circular_slider: ^2.0.1
  auto_size_text: ^3.0.0
  fl_chart: ^0.61.0
  flutter_svg: ^2.0.2
  double_back_to_close_app: ^2.1.0
  video_player: ^2.5.3
  dotted_dashed_line: ^0.0.3
  step_progress_indicator: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
#  flutter_launcher_icons: "^0.9.2"
#  flutter_launcher_name: "^0.0.1"
  flutter_native_splash: ^2.2.4

flutter_native_splash:
  color: "#1f232c"
  image: assets/splash.png

flutter_launcher_name:
  name: "Smart House"

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/app_icon.png"


flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/footer/
    - assets/devices/
    - assets/device_control/
    - assets/cameras/
    - assets/account/
    - assets/icons_images/

  fonts:
    - family: ProductSans
      fonts:
        - asset: fonts/ProductSans-Regular.ttf
        - asset: fonts/ProductSans-Medium.ttf
        - asset: fonts/ProductSans-Bold.ttf

flutter_intl:
  enabled: true